[build-system]
requires = ["custom-build@git+https://github.com/jaraco/custom-build", "setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4.1"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
